version: "3"
   
services:
  db:
    restart: always
    image: postgres
    env_file:
      - .env
  redis:
    restart: always
    image: redis:latest
  rqworker:
    restart: always
    build: .
    volumes:
      - .:/code
    command: python project_balls/manage.py rqworker
  rqworker_high:
    restart: always
    build: .
    volumes:
      - .:/code
    command: python project_balls/manage.py rqworker high
  web:
    restart: always
    build: .
    command: bash -c "python project_balls/manage.py makemigrations && python project_balls/manage.py migrate && python project_balls/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rqworker
      - rqworker_high
    env_file:
      - .env

