# Generated by Django 3.1.3 on 2020-11-28 18:53

from django.db import migrations
import sorl.thumbnail.fields
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_boardmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(default='images/default-thumbnail.png', upload_to='users/thumbnails'),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='videoFile',
            field=video_encoding.fields.VideoField(upload_to='users/videos'),
        ),
    ]
