# Generated by Django 3.1.3 on 2020-11-28 19:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201128_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='users/thumbnails'),
        ),
    ]
