# Generated by Django 3.1.3 on 2020-11-29 02:37

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201129_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(default='settings.MEDIA_ROOT/images/default-thumbnail.png', upload_to='users/thumbnails'),
        ),
    ]
