# Generated by Django 3.1.3 on 2020-11-29 07:43

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201129_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(default='images/default-thumbnail.jpg', upload_to='users/thumbnails'),
        ),
    ]
