# Generated by Django 3.1.3 on 2020-12-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201129_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
