# Generated by Django 3.1.3 on 2020-12-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201201_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='useSelect',
        ),
    ]
