# Generated by Django 3.1.3 on 2020-12-01 13:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_user_useselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='primaryTags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
        migrations.CreateModel(
            name='SnippetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None)),
                ('Board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boardmodel')),
            ],
        ),
    ]
