# Generated by Django 3.1.3 on 2020-12-05 16:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201202_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allTags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
    ]
