# Generated by Django 3.1.3 on 2020-12-06 00:55

from django.db import migrations
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_user_alltags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippetmodel',
            name='videoFile',
            field=video_encoding.fields.VideoField(upload_to='users/snippets'),
        ),
    ]
