# Generated by Django 3.1.3 on 2020-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201206_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cancel_recording_key',
            field=models.IntegerField(default=67),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_recording_key',
            field=models.IntegerField(default=83),
        ),
    ]
