# Generated by Django 3.1.4 on 2021-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210501_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='tagStatistics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='tagStatistics',
            field=models.JSONField(default=dict),
        ),
    ]
