# Generated by Django 3.1.4 on 2021-05-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210501_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='tagStatistics',
            new_name='snippetStatistics',
        ),
        migrations.AddField(
            model_name='user',
            name='snippetStatistics',
            field=models.JSONField(default=dict),
        ),
    ]
